[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Created By <a class="text-muted" href="https://github.com/DavidWiseman">David Wiseman</a> <a class="text-muted" href="https://trimble.com">Copyright © 2022 Trimble, Inc</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

